
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1205, 914)
        self.startBtn = QtWidgets.QPushButton(Form)
        self.startBtn.setGeometry(QtCore.QRect(980, 670, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.startBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("startBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startBtn.setIcon(icon)
        self.startBtn.setIconSize(QtCore.QSize(20, 20))
        self.startBtn.setDefault(False)
        self.startBtn.setObjectName("startBtn")
        self.quitBtn = QtWidgets.QPushButton(Form)
        self.quitBtn.setGeometry(QtCore.QRect(1100, 670, 89, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quitBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitBtn.setIcon(icon1)
        self.quitBtn.setIconSize(QtCore.QSize(20, 20))
        self.quitBtn.setObjectName("quitBtn")
        self.videolabel = QtWidgets.QLabel(Form)
        self.videolabel.setGeometry(QtCore.QRect(20, 110, 801, 601))
        self.videolabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videolabel.setText("")
        self.videolabel.setPixmap(QtGui.QPixmap("f68344aaecc56cc0c1654e32ee07e94f.jpg"))
        self.videolabel.setOpenExternalLinks(False)
        self.videolabel.setObjectName("videolabel")
        self.recoFaceLabel = QtWidgets.QLabel(Form)
        self.recoFaceLabel.setGeometry(QtCore.QRect(850, 120, 341, 531))
        self.recoFaceLabel.setStyleSheet("color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));")
        self.recoFaceLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.recoFaceLabel.setObjectName("recoFaceLabel")
        self.label_0 = QtWidgets.QLabel(Form)
        self.label_0.setGeometry(QtCore.QRect(320, 50, 181, 51))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_0.setFont(font)
        self.label_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_0.setFrameShape(QtWidgets.QFrame.Box)
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(30, 730, 161, 171))
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 730, 161, 171))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(440, 730, 161, 171))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 730, 161, 171))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 710, 1221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(830, 50, 20, 671))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-3, 40, 1201, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setGeometry(QtCore.QRect(20, 110, 271, 51))
        self.timeLabel.setObjectName("timeLabel")
        self.pauseBtn = QtWidgets.QPushButton(Form)
        self.pauseBtn.setGeometry(QtCore.QRect(860, 670, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pauseBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseBtn.setIcon(icon2)
        self.pauseBtn.setIconSize(QtCore.QSize(30, 30))
        self.pauseBtn.setObjectName("pauseBtn")
        self.logLabel = QtWidgets.QLabel(Form)
        self.logLabel.setGeometry(QtCore.QRect(860, 80, 221, 31))
        self.logLabel.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel.setObjectName("logLabel")
        self.videolabel.raise_()
        self.startBtn.raise_()
        self.quitBtn.raise_()
        self.recoFaceLabel.raise_()
        self.label_0.raise_()
        self.label_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_4.raise_()
        self.timeLabel.raise_()
        self.pauseBtn.raise_()
        self.logLabel.raise_()

        self.retranslateUi(Form)
        self.quitBtn.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.startBtn.setText(_translate("Form", "开始"))
        self.quitBtn.setText(_translate("Form", "退出"))
        self.recoFaceLabel.setText(_translate("Form", "<html><head/><body><p>未检测到人脸</p></body></html>"))
        self.label_0.setText(_translate("Form", "  视频采集区"))
        self.timeLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fce94f;\">2019年4月1日12:05</span></p></body></html>"))
        self.pauseBtn.setText(_translate("Form", "暂停"))
        self.logLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">日志:</span></p></body></html>"))

