# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1206, 956)
        self.videolabel = QtWidgets.QLabel(Form)
        self.videolabel.setGeometry(QtCore.QRect(20, 110, 801, 601))
        self.videolabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videolabel.setText("")
        self.videolabel.setPixmap(QtGui.QPixmap("f68344aaecc56cc0c1654e32ee07e94f.jpg"))
        self.videolabel.setOpenExternalLinks(False)
        self.videolabel.setObjectName("videolabel")
        self.label_0 = QtWidgets.QLabel(Form)
        self.label_0.setGeometry(QtCore.QRect(320, 50, 181, 51))
        font = QtGui.QFont()
        font.setFamily("KacstArt")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_0.setFont(font)
        self.label_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_0.setFrameShape(QtWidgets.QFrame.Box)
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(30, 730, 161, 171))
        self.label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 730, 161, 171))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(440, 730, 161, 171))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 730, 161, 171))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 710, 1221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(830, 50, 20, 671))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-3, 40, 1201, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setGeometry(QtCore.QRect(20, 110, 271, 51))
        self.timeLabel.setObjectName("timeLabel")
        self.logLabel = QtWidgets.QLabel(Form)
        self.logLabel.setGeometry(QtCore.QRect(860, 80, 221, 31))
        self.logLabel.setTextFormat(QtCore.Qt.AutoText)
        self.logLabel.setObjectName("logLabel")
        self.recoFaceLabel = QtWidgets.QTextBrowser(Form)
        self.recoFaceLabel.setGeometry(QtCore.QRect(860, 110, 341, 601))
        self.recoFaceLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.recoFaceLabel.setObjectName("recoFaceLabel")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(850, 730, 331, 161))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.startBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.startBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("startBtn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startBtn.setIcon(icon)
        self.startBtn.setIconSize(QtCore.QSize(20, 20))
        self.startBtn.setDefault(False)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout.addWidget(self.startBtn, 0, 1, 1, 1)
        self.deleteBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.deleteBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteBtn.setIcon(icon1)
        self.deleteBtn.setIconSize(QtCore.QSize(20, 20))
        self.deleteBtn.setObjectName("deleteBtn")
        self.gridLayout.addWidget(self.deleteBtn, 1, 0, 1, 1)
        self.quitBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quitBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitBtn.setIcon(icon2)
        self.quitBtn.setIconSize(QtCore.QSize(20, 20))
        self.quitBtn.setObjectName("quitBtn")
        self.gridLayout.addWidget(self.quitBtn, 1, 1, 1, 1)
        self.logDelBtn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.logDelBtn.setFont(font)
        self.logDelBtn.setIcon(icon1)
        self.logDelBtn.setIconSize(QtCore.QSize(20, 20))
        self.logDelBtn.setObjectName("logDelBtn")
        self.gridLayout.addWidget(self.logDelBtn, 0, 0, 1, 1)
        self.videolabel.raise_()
        self.startBtn.raise_()
        self.quitBtn.raise_()
        self.label_0.raise_()
        self.label_1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_4.raise_()
        self.timeLabel.raise_()
        self.logLabel.raise_()
        self.deleteBtn.raise_()
        self.recoFaceLabel.raise_()

        self.retranslateUi(Form)
        self.quitBtn.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_0.setText(_translate("Form", "  视频采集区"))
        self.timeLabel.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#fce94f;\">2019年4月1日12:05</span></p></body></html>"))
        self.logLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">日志:</span></p></body></html>"))
        self.recoFaceLabel.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">显示日志：</p></body></html>"))
        self.startBtn.setText(_translate("Form", "开始"))
        self.deleteBtn.setText(_translate("Form", "图片清空"))
        self.quitBtn.setText(_translate("Form", "退出"))
        self.logDelBtn.setText(_translate("Form", "日志清空"))

